In [2]:
from ch06 import svmMLiA

In [3]:
dataMat,labelMat = svmMLiA.loadDataSet('/Users/JD.K/Downloads/machinelearninginaction/Ch06/testSet.txt')
# print(labelMat)
# b,alphas = svmMLiA.smoSimple(dataMat,labelMat,0.6,0.001,40)
# print('b = ',b)
# print(alphas[alphas>0])
# for i in range(100):
#     if alphas[i] > 0:
#         print(dataMat[i],labelMat[i])

b,alphas = svmMLiA.smoP(dataMat,labelMat,0.6,0.001,40)
print('b = ',b)
print(alphas[alphas>0])
for i in range(100):
    if alphas[i] > 0:
        print(dataMat[i],labelMat[i])

L == H
fullSet,iter: 0 i 0, pairs changed 0
L == H
fullSet,iter: 0 i 1, pairs changed 0
fullSet,iter: 0 i 2, pairs changed 1
fullSet,iter: 0 i 3, pairs changed 2
j not moving enough
fullSet,iter: 0 i 4, pairs changed 2
j not moving enough
fullSet,iter: 0 i 5, pairs changed 2
j not moving enough
fullSet,iter: 0 i 6, pairs changed 2
fullSet,iter: 0 i 7, pairs changed 2
fullSet,iter: 0 i 8, pairs changed 2
fullSet,iter: 0 i 9, pairs changed 2
fullSet,iter: 0 i 10, pairs changed 2
fullSet,iter: 0 i 11, pairs changed 2
fullSet,iter: 0 i 12, pairs changed 2
fullSet,iter: 0 i 13, pairs changed 2
fullSet,iter: 0 i 14, pairs changed 2
j not moving enough
fullSet,iter: 0 i 15, pairs changed 2
fullSet,iter: 0 i 16, pairs changed 2
fullSet,iter: 0 i 17, pairs changed 2
j not moving enough
fullSet,iter: 0 i 18, pairs changed 2
fullSet,iter: 0 i 19, pairs changed 2
fullSet,iter: 0 i 20, pairs changed 2
fullSet,iter: 0 i 21, pairs changed 2
j not moving enough
fullSet,iter: 0 i 22, pairs changed 2
fu


fullSet,iter: 2 i 66, pairs changed 0
fullSet,iter: 2 i 67, pairs changed 0
fullSet,iter: 2 i 68, pairs changed 0
fullSet,iter: 2 i 69, pairs changed 0
fullSet,iter: 2 i 70, pairs changed 0
fullSet,iter: 2 i 71, pairs changed 0
fullSet,iter: 2 i 72, pairs changed 0
fullSet,iter: 2 i 73, pairs changed 0
fullSet,iter: 2 i 74, pairs changed 0
fullSet,iter: 2 i 75, pairs changed 0
j not moving enough
fullSet,iter: 2 i 76, pairs changed 0
fullSet,iter: 2 i 77, pairs changed 0
fullSet,iter: 2 i 78, pairs changed 0
fullSet,iter: 2 i 79, pairs changed 0
fullSet,iter: 2 i 80, pairs changed 0
fullSet,iter: 2 i 81, pairs changed 0
fullSet,iter: 2 i 82, pairs changed 0
fullSet,iter: 2 i 83, pairs changed 0
j not moving enough
fullSet,iter: 2 i 84, pairs changed 0
fullSet,iter: 2 i 85, pairs changed 0
fullSet,iter: 2 i 86, pairs changed 0
fullSet,iter: 2 i 87, pairs changed 0
fullSet,iter: 2 i 88, pairs changed 0
fullSet,iter: 2 i 89, pairs changed 0
fullSet,iter: 2 i 90, pairs changed 0
fullSet,i

In [4]:
ws = svmMLiA.calcWs(alphas,dataMat,labelMat)

In [6]:
b

matrix([[-2.06657148]])

In [5]:
type(dataMat)

list

In [7]:
import numpy as np

In [8]:
matrix = np.mat(dataMat)

In [9]:
matrix[0]*np.mat(ws)+b

matrix([[-0.56033809]])

In [10]:
matrix[2]*np.mat(ws)+b

matrix([[ 2.03782213]])

In [11]:
matrix[1]*np.mat(ws)+b

matrix([[-0.91730498]])

In [12]:
svmMLiA.testRbf()

AttributeError: module 'ch06.svmMLiA' has no attribute 'testRbf'